version: '3.7'
services:
  es:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.5.0'
    container_name: es01
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro'
    networks:
      - efknet
    restart: on-failure
  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.5.0'
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: 'http://es:9200'
    ports:
      - 5601:5601
    networks:
      - efknet
    depends_on:
      - es
    restart: on-failure
    logging: { driver: none }

  # fluent-bit:
  #   image: fluent/fluent-bit
  #   restart: on-failure
  #   volumes:
  #     - './fluent-bit:/etc/fluent-bit'
  #     - '/Volumes/Data/www/sitesoft/bpextra/storage/logs:/var/logs'
  #   command:
  #     /fluent-bit/bin/fluent-bit --config=/etc/fluent-bit/fluent.conf
  #   depends_on:
  #     - es
  #   networks:
  #     - efknet

#   fluentd:
#     image: fluentd
#     restart: on-failure
#     ports:
#       - 4560/udp
#     environment:
#       ELASTIC_HOSTS: 'es:9200'
#       LISTEN_PORT: 5160
#       LOGSTASH_PREFIX: app-name
#       LOGSTASH_DATEFORMAT: '%Y-%m-%d'
#     volumes:
#       - './fluent/fluent.conf:/fluentd/etc/fluent.conf:ro'
#       - '/Volumes/Data/www/sitesoft/bpextra/storage/logs:/logs'
#     depends_on:
#       - es
#     networks:
#       - efknet
networks:
  efknet: null
